name: ExamYaml
on:
  push:
    branches:
      - random_forest_experiment
permissions:
  id-token: write
  contents: write
jobs:
  first-job:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2
      - name: Model Training
        env:
          REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          pip install -r requirements.txt
          python File.py
      - name: Get-CML-Results
        env:
          REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          echo "#Results">report.md
          cat results.txt>>report.md
          cml comment create report.md

