name: ExamYaml
  on:
    push:
      branches:
        - lasso_experiment
permissions:
  id-token: write
  contents: write
jobs:
  FirstJob:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2
      - name: Model-Training-Step
        env:
          REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          pip install -r requirements.txt
          python File.py
      - name: CML-Results
        env:
          REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          echo "#Results">report.md
          cat results.txt>>report.md
          cml comment create report.md